### ISSUE TITLE
Proofreading

### ISSUE THREAD

**Issue by legoman77** [skilstak/pro#1]
Schedule:
- On line 23, you use past tense, but you use present tense everywhere else.  I suggest changing line 23 to "Create TODO Issues".
- There is no information about Peer Reviews on the schedule.  Do Peer Reviews still have deadlines?  The Peer Review document also doesn't say anything about deadlines.  I recommend making this clearer.

**Comment by robmuh** [comment]
No Peer Review anymore now that the project repos are private. This has pros and cons.
